/**
 * AGENTS.md template generator — V13 of Direction B
 *
 * Renders a `AGENTS.md` markdown file from a list of ADRs. The file
 * is intended to be dropped into a repo root and read by any AI coding
 * agent (Claude Code, Codex, Cursor, etc) at session start.
 *
 * Sections per ADR:
 *   - ### <title>
 *   - **Status / Source / Date** metadata
 *   - **Context**
 *   - **Decision**
 *   - **Alternatives** (if any)
 *   - **Affects** (linked files)
 *
 * At the top, a summary table with title + status + tradeoffScore.
 */
import type { ArchitectureDecisionRecord } from "../types.js";

export interface AgentsMdOptions {
  /** Project name. Default: "this project". */
  projectName?: string;
  /** Generated-at timestamp. Default: new Date().toISOString(). */
  generatedAt?: string;
  /** Only include ADRs with these sources. Default: all. */
  onlySources?: ReadonlyArray<string>;
  /** Max number of ADRs to render. Default: 100. */
  maxRecords?: number;
}

/** Render a single ADR section (markdown). */
export function renderAdrSection(d: ArchitectureDecisionRecord): string {
  const lines: string[] = [];
  lines.push(`### ${d.title}`);
  lines.push("");
  const meta: string[] = [
    `**Status**: \`${d.status}\``,
    `**Source**: \`${d.source}\``,
    `**Date**: ${d.date}`,
  ];
  if (typeof d.tradeoffScore === "number") {
    meta.push(`**Tradeoff**: ${d.tradeoffScore.toFixed(2)}`);
  }
  lines.push(meta.join(" · "));
  lines.push("");
  if (d.context) {
    lines.push("**Context**");
    lines.push("");
    lines.push(d.context);
    lines.push("");
  }
  lines.push("**Decision**");
  lines.push("");
  lines.push(d.decision);
  lines.push("");
  if (d.alternatives.length > 0) {
    lines.push("**Alternatives considered**");
    lines.push("");
    for (const a of d.alternatives) {
      lines.push(`- **${a.name}** — ${a.whyRejected}`);
    }
    lines.push("");
  }
  if (d.linkedNodeIds.length > 0) {
    lines.push("**Affects**");
    lines.push("");
    for (const nid of d.linkedNodeIds) {
      // strip "file:" prefix for readability
      const clean = nid.startsWith("file:") ? nid.slice(5) : nid;
      lines.push(`- \`${clean}\``);
    }
    lines.push("");
  }
  return lines.join("\n");
}

/** Render the full AGENTS.md. */
export function renderAgentsMd(
  decisions: ReadonlyArray<ArchitectureDecisionRecord>,
  options: AgentsMdOptions = {},
): string {
  const projectName = options.projectName ?? "this project";
  const generatedAt = options.generatedAt ?? new Date().toISOString();
  const maxRecords = options.maxRecords ?? 100;
  const allowedSources = options.onlySources
    ? new Set(options.onlySources)
    : null;

  const filtered = decisions
    .filter((d) => (allowedSources ? allowedSources.has(d.source) : true))
    .slice(0, maxRecords);

  const lines: string[] = [];
  lines.push(`# AGENTS.md — ${projectName}`);
  lines.push("");
  lines.push(
    `> Auto-generated by \`/understand-decisions\` at ${generatedAt}. ` +
      `This file lists every architecture decision in the repo. ` +
      `AI agents: read this first when you need to know "why is this code the way it is?".`,
  );
  lines.push("");
  lines.push(`**${filtered.length} decision${filtered.length === 1 ? "" : "s"} documented.**`);
  lines.push("");

  // Summary table
  if (filtered.length > 0) {
    lines.push("## Summary");
    lines.push("");
    lines.push("| # | Title | Status | Source | Tradeoff |");
    lines.push("|---|-------|--------|--------|----------|");
    filtered.forEach((d, i) => {
      const tradeoff =
        typeof d.tradeoffScore === "number" ? d.tradeoffScore.toFixed(2) : "—";
      lines.push(`| ${i + 1} | ${d.title.replace(/\|/g, "\\|")} | ${d.status} | ${d.source} | ${tradeoff} |`);
    });
    lines.push("");
  }

  // Detail sections
  lines.push("## Decisions");
  lines.push("");
  for (const d of filtered) {
    lines.push(renderAdrSection(d));
  }

  if (filtered.length === 0) {
    lines.push("No decisions recorded yet. Run `/understand-decisions` to extract ADRs from git history and code comments.");
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * V14 — Convenience: write AGENTS.md to a target path.
 * Returns the bytes written and the file path.
 */
export async function writeAgentsMd(
  outPath: string,
  decisions: ReadonlyArray<ArchitectureDecisionRecord>,
  options: AgentsMdOptions = {},
): Promise<{ path: string; bytes: number }> {
  const text = renderAgentsMd(decisions, options);
  const { writeFile, mkdir } = await import("node:fs/promises");
  const { dirname } = await import("node:path");
  await mkdir(dirname(outPath), { recursive: true });
  await writeFile(outPath, text, "utf8");
  return { path: outPath, bytes: Buffer.byteLength(text, "utf8") };
}
